### ISSUE TITLE
A lot of needless compilation...

### ISSUE THREAD

**Issue by 3dluvr** [Wamphyre/BSD-XFCE#4]
I thought to give this a try and after doing a fresh 13.1 install on a spare SSD, I proceeded to run your script.

Everything seemed ok until I noticed that it started compiling things like libgettext from the ports tree even though a package is available. From there on, it only got worse when I saw it start compiling the entire Qt5. Seriously?!

I thought it would be done fast but after 1 hr I gave up and stopped the compilation. This is on a dual Xeon with 16 cores by the way and Nvidia GTX Titan.

Suffice to say I restarted the script without the "creative suite" where it stopped and after a reboot, the system got stuck on the FreeBSD splash screen and wouldn't go any further.

This is a valiant effort, but it needs more polish.

**Comment by Wamphyre** [comment]
Hi @3dluvr thanks for your feedback!

You're right about the compilation times of the "creative suite", they are too long in some scenarios. We can try a different approach.

I just modified the main script to install the suitable "creative suite" applications using `pkg` instead of compiling, but `lmms` still needs to be compiled from ports because it doesn't ship with JACK support by default. 

Anyway, the installation times are now a lot shorter.

[Changelog here](https://github.com/Wamphyre/BSD-XFCE/commit/b8a2f758c3a43f85f0676fd2b1a24d34fc33d03d)

About the boot problem, maybe is related to some `/boot/loader.conf` and `/etc/sysctl.conf` parameters. More specific the CPU mitigation disabling. So I just removed:

[loader.conf](https://github.com/Wamphyre/BSD-XFCE/commit/114cd63d601c62834b6ffca256f182d295e828c9)
[sysctl.conf](https://github.com/Wamphyre/BSD-XFCE/commit/9c0641737dbcb23a610aa0c5378f4fd10bb5c2b2)

If you want to enable boot logging instead of the FreeBSD splash you can change `boot_mute=YES` to `boot_mute=NO` in `/boot/loader.conf` to get info about the start process and see the system messages that could give us more information about the problem.

Greetings!

**Comment by 3dluvr** [comment]
Thanks for updating the setup script.

Regarding booting issue, after some headache I noticed that ZFS wasn't being auto-mounted, so adding zfs_enable="YES" in /etc/rc.conf kinda fixed that. (FreeBSD 13.1)

Then with NVIDIA driver, I think everyone needs to read-up on proper installation because depending which card they have they might need to use an earlier driver and not the latest one (510 as of this writing). In my case I have a GTX Titan so I had to go to 490.

Another issue is that between nvidia vs nvidia-modeset kernel module. Again, the latter is for the newer cards, IIRC.

I think I would suggest setting boot_mute="NO" by default at first and allow 3-5 seconds timer before booting.

Also, an update to the README to note that the other 2 steps that user needs to perform are done *after* the reboot. I think the "post-installation" is kinda ambiguous because it might suggest it's good to go right away but it actually pends a reboot.

Perhaps instead of automatically installing the "creative suite" that should be optional, allowing users to go back to doing that after they've ensure the system boots up correctly and everything is to their liking. Maybe just make a side script for the it?

Hope this helps!

**Comment by Wamphyre** [comment]
Hi @3dluvr I just made a huge amount of changes in the scripts, system configs, README, etc...Based on your fantastic suggerences

Now, the project itself it's very well self-documented, so the chances of errors are now very minimal if the user reads the updated comments in the code and the README file. 

Now, the creative suite are now an independent and optional installation script so the core system install it's very polished and quick in this new 2.0 version :)

Thank you very much!
