### ISSUE TITLE
Problems post installation

### ISSUE THREAD

**Issue by pieroproietti** [Wamphyre/BSD-XFCE#7]
Hi @Wamphyre,

I'm on a VM on proxmox VE, playing with FreeBSD. I successully installed FreeBSD and GostBSD, today looking your project I tried to install it, and:
* installed a fresh FreeBSD-13.1-RELEASE-amd64-disc1.iso
* ```sudo git clone https://github.com/Wamphyre/BSD-XFCE && sh BSD-XFCE/xfce_desktop.sh```

All went OK without errors, but when I restarted I had this

![bsd-xfce-error](https://user-images.githubusercontent.com/958613/206839485-3bf9ddd3-27e4-49ed-b6c3-5d6bdac408eb.png)

That I can do to overpass?

**Comment by Wamphyre** [comment]
Hi @pieroproietti glad to see you here :)

I see you're using ZFS instead UFS, that looks like a problem with the ZFS module is not loaded because is not present in the configuration files of my project. I must fix that.

If you can mount your partition by other ways you can restore the backups of `/boot/loader.conf `and `/etc/sysctl.conf `made during the installation.

Thank you very much for your contact!

**Comment by pieroproietti** [comment]
Hi @Wamphyre 

I will repeat the experiment with UFS, I simply don't know at all it, so I decided to use zfs just to feelme a bit more at home. 

I started the last week to investigate that can I do with FreeBSD to adapt eggs to it and want to ask you if there is a FreeSBD way to get a live system, and if you have spare time to assist/collaborate for that.

We can work directly on a branch of penguins-eggs  or open a new project - something like daemons-eggs - because the differences are too much to have all in an unique base, at least until we can get something who can work and have more clear ideas.

Thank you for the idea!

**Comment by Wamphyre** [comment]
Hi @pieroproietti glad to see the script worked on your installation! 

As you know, FreeBSD is a different beast even in the use-case or filesystem choose.

For example, ZFS are more suitable for fileservers, webservers, etc. And UFS (Unix FIlesystem) is the classic and simpler filesystem recommended for desktop, workstations, etc...I always use UFS for desktops.

For `penguin-eggs` I think we can use an UFS installation because of simplicity, similar to EXT4 on GNU/Linux.

I will try to collaborate in the project in my spare time, I really love the idea of using penguin-eggs on BSD system :) 

For the construction of custom BSD-Live systems, I know about some scripts that we can try to adapt or study:

For example: https://github.com/nomadbsd/NomadBSD

Or, the more actual resource: https://github.com/helloSystem/ISO

About `spice-vdagent` I know this is deprecated in BSD, but we have a (maybe) viable alternative here:

https://www.freshports.org/devel/spice-protocol/

Thank you very much for your contact!!
